# -*- coding: utf-8 -*-
"""Image Generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1by_5btTN3CGYaDkfD5_Y7TXspAI2xrPB
"""

!pip install openai requests

# Replace with your actual API key
client = OpenAI(api_key="your api key")

def filename_from_input(prompt):
    # Make the filename lowercase and replace spaces with underscores
    safe_name = prompt.lower().replace(" ", "_")
    return f"{safe_name}.png"

def download_image(filename, url):
    response = requests.get(url)
    if response.status_code == 200:
        with open(filename, 'wb') as f:
            f.write(response.content)
        print(f"Image saved as {filename}")
    else:
        print("Failed to download image.")

def get_image(prompt, model="dall-e-2"):
    response = client.images.generate(
        model=model,
        prompt=prompt,
        n=1,
        size="512x512"
    )
    image_url = response.data[0].url
    filename = filename_from_input(prompt)
    download_image(filename, image_url)

prompt = "images of a punjabi dish called a samosa"
get_image(prompt)

display(Image(filename_from_input(prompt)))

def generate_and_display(prompt):
    get_image(prompt)
    display(Image(filename_from_input(prompt)))

# Example use
generate_and_display("images of a punjabi dish called a samosa")